spring:
  thymeleaf:
    # 템플릿 파일 위치 설정 기본값은 templates
    prefix: classpath:templates/thymeleaf/
    # Thymeleaf 템플릿 파일의 확장자를 지정 , 기본값 .html
    suffix: .html
    # 템플릿 캐시는 템플릿 파일을 미리 컴파일하여 성능을 향상시키는데 사용되며, 개발 중에는 주로 캐시를 비활성화하여 변경 사항을 빠르게 반영할 수 있도록 합니다.
    # 프로덕션 환경에서는 캐시를 활성화하는 것이 권장
    cache: false
